// SPDX-License-Identifier: GPL-3.0-or-later
//! Wire protocol shared between the midnightsnack host and every remote.
//!
//! All types derive [`ts_rs::TS`]; `pnpm gen:types` regenerates the TypeScript bindings in
//! `packages/protocol/src/generated`. Messages are JSON, internally tagged with a `type` field.
//! See `docs/dev/protocol.md` for the full specification.

mod action;
mod connectivity;
mod control;
mod error;
mod messages;
mod openslides;
mod pairing;
mod state;

pub use action::*;
pub use connectivity::*;
pub use control::*;
pub use error::*;
pub use messages::*;
pub use openslides::*;
pub use pairing::*;
pub use state::*;

/// Version of the wire protocol. Bumped on every breaking change.
pub const PROTOCOL_VERSION: u32 = 1;

/// Default TCP port of the embedded server.
pub const DEFAULT_PORT: u16 = 4747;

/// DNS-SD service type advertised by hosts.
pub const MDNS_SERVICE_TYPE: &str = "_midnightsnack._tcp.local.";

/// Writes non-type constants next to the ts-rs bindings.
#[cfg(test)]
#[test]
fn export_bindings_constants() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "./bindings".into());
    let dir = std::path::Path::new(&dir);
    std::fs::create_dir_all(dir).expect("create export dir");
    let body = format!(
        "// This file is generated by crates/protocol. Do not edit.\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n\
         export const DEFAULT_PORT = {DEFAULT_PORT};\n\
         export const DEFAULT_HTTPS_PORT = {DEFAULT_HTTPS_PORT};\n\
         export const RELAY_NOISE_PATTERN = \"{RELAY_NOISE_PATTERN}\";\n\
         export const RELAY_PROLOGUE = {prologue};\n\
         export const TUNNEL_HEADER = {TUNNEL_HEADER};\n\
         export const OS_AGENDA_PAGE_SIZE = {OS_AGENDA_PAGE_SIZE};\n\
         export const TUNNEL_MAX_PAYLOAD = {TUNNEL_MAX_PAYLOAD};\n\
         export const TUNNEL = {{\n  WS_MESSAGE: {},\n  REQUEST_HEAD: {},\n  REQUEST_BODY: {},\n  \
         RESPONSE_HEAD: {},\n  RESPONSE_BODY: {},\n  RESET: {},\n  PING: {},\n  PONG: {},\n  \
         WS_CLOSE: {},\n  FIN: {},\n}} as const;\n\
         export const RELAY_CLOSE = {{\n  HOST_OFFLINE: {},\n  HOST_FULL: {},\n  \
         RATE_LIMITED: {},\n  CLOSED_BY_HOST: {},\n}} as const;\n",
        tunnel::WS_MESSAGE,
        tunnel::REQUEST_HEAD,
        tunnel::REQUEST_BODY,
        tunnel::RESPONSE_HEAD,
        tunnel::RESPONSE_BODY,
        tunnel::RESET,
        tunnel::PING,
        tunnel::PONG,
        tunnel::WS_CLOSE,
        tunnel::FIN,
        relay_close::HOST_OFFLINE,
        relay_close::HOST_FULL,
        relay_close::RATE_LIMITED,
        relay_close::CLOSED_BY_HOST,
        prologue = serde_json::to_string(RELAY_PROLOGUE).expect("json"),
    );
    std::fs::write(dir.join("constants.ts"), body).expect("write constants.ts");
}

#[cfg(test)]
mod tests;
