// SPDX-License-Identifier: GPL-3.0-or-later
//! Wire protocol shared between the midnightsnack host and every remote.
//!
//! All types derive [`ts_rs::TS`]; running `cargo test -p midnightsnack-protocol`
//! regenerates the TypeScript bindings in `packages/protocol/src/generated`.
//! Messages are JSON, internally tagged with a `type` field.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Version of the wire protocol. Bumped on every breaking change.
pub const PROTOCOL_VERSION: u32 = 1;

/// Permission level of a connected device. Ordered from least to most privileged.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum Role {
    StageViewer,
    Presenter,
    Operator,
    Admin,
}

/// Static information about a host, returned before pairing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct HostInfo {
    pub name: String,
    pub app_version: String,
    pub protocol_version: u32,
}

/// Messages sent from a remote to the host.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
#[ts(export)]
pub enum ClientMessage {
    /// First message on every connection.
    Hello {
        protocol_version: u32,
    },
    Ping {
        nonce: u32,
    },
}

/// Messages sent from the host to a remote.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
#[ts(export)]
pub enum ServerMessage {
    Welcome {
        host: HostInfo,
    },
    Pong {
        nonce: u32,
    },
    /// A request failed. `code` is a stable, translatable identifier.
    Error {
        code: ErrorCode,
    },
}

/// Stable error identifiers. User-facing text lives in the frontend locale files.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum ErrorCode {
    ProtocolMismatch,
    MalformedMessage,
    Unauthorized,
    Forbidden,
}

/// Writes non-type constants next to the ts-rs bindings.
#[cfg(test)]
#[test]
fn export_bindings_constants() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "./bindings".into());
    let dir = std::path::Path::new(&dir);
    std::fs::create_dir_all(dir).expect("create export dir");
    let body = format!(
        "// This file is generated by crates/protocol. Do not edit.\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    );
    std::fs::write(dir.join("constants.ts"), body).expect("write constants.ts");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T>(value: &T) -> T
    where
        T: Serialize + for<'de> Deserialize<'de>,
    {
        let json = serde_json::to_string(value).expect("serialize");
        serde_json::from_str(&json).expect("deserialize")
    }

    #[test]
    fn client_messages_round_trip() {
        let msgs = [
            ClientMessage::Hello {
                protocol_version: PROTOCOL_VERSION,
            },
            ClientMessage::Ping { nonce: 7 },
        ];
        for m in msgs {
            assert_eq!(round_trip(&m), m);
        }
    }

    #[test]
    fn server_messages_round_trip() {
        let msgs = [
            ServerMessage::Welcome {
                host: HostInfo {
                    name: "Stage left".into(),
                    app_version: "0.0.1".into(),
                    protocol_version: PROTOCOL_VERSION,
                },
            },
            ServerMessage::Pong { nonce: 1 },
            ServerMessage::Error {
                code: ErrorCode::Forbidden,
            },
        ];
        for m in msgs {
            assert_eq!(round_trip(&m), m);
        }
    }

    #[test]
    fn wire_format_is_tagged_snake_case() {
        let json = serde_json::to_value(ClientMessage::Ping { nonce: 3 }).unwrap();
        assert_eq!(json, serde_json::json!({ "type": "ping", "nonce": 3 }));
    }

    #[test]
    fn roles_are_ordered_by_privilege() {
        assert!(Role::Admin > Role::Operator);
        assert!(Role::Operator > Role::Presenter);
        assert!(Role::Presenter > Role::StageViewer);
    }
}
