// SPDX-License-Identifier: GPL-3.0-or-later
//! Wire protocol shared between the midnightsnack host and every remote.
//!
//! All types derive [`ts_rs::TS`]; `pnpm gen:types` regenerates the TypeScript bindings in
//! `packages/protocol/src/generated`. Messages are JSON, internally tagged with a `type` field.
//! See `docs/dev/protocol.md` for the full specification.

mod action;
mod error;
mod messages;
mod pairing;
mod state;

pub use action::*;
pub use error::*;
pub use messages::*;
pub use pairing::*;
pub use state::*;

/// Version of the wire protocol. Bumped on every breaking change.
pub const PROTOCOL_VERSION: u32 = 1;

/// Default TCP port of the embedded server.
pub const DEFAULT_PORT: u16 = 4747;

/// DNS-SD service type advertised by hosts.
pub const MDNS_SERVICE_TYPE: &str = "_midnightsnack._tcp.local.";

/// Writes non-type constants next to the ts-rs bindings.
#[cfg(test)]
#[test]
fn export_bindings_constants() {
    let dir = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "./bindings".into());
    let dir = std::path::Path::new(&dir);
    std::fs::create_dir_all(dir).expect("create export dir");
    let body = format!(
        "// This file is generated by crates/protocol. Do not edit.\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n\
         export const DEFAULT_PORT = {DEFAULT_PORT};\n"
    );
    std::fs::write(dir.join("constants.ts"), body).expect("write constants.ts");
}

#[cfg(test)]
mod tests;
