[package]
name = "midnightsnack-capture"
description = "Screen and window capture for midnightsnack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bytes = "1"
image = { version = "0.25", default-features = false }
jpeg-encoder = "0.6"
midnightsnack-protocol.workspace = true
tokio = { version = "1", features = ["sync"] }
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(not(target_os = "linux"))'.dependencies]
xcap = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["randr"] }

[lints]
workspace = true
